import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Cart | Bootcamp ADA CIELO",
  description: "Generated by create next app. Created by myself",
};

export default function CartLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section>{children}</section>;
}
